"""
NIFTY 250 UNIVERSE — Current composition (Nifty LargeMidcap 250)
Note: Uses current composition → survivorship bias acknowledged.
Stocks listed after 2011 will have partial backtest data (from IPO date).
"""

NIFTY_250_STOCKS = {
    # ── NIFTY 50 ────────────────────────────────────────────────────────────
    'ADANIPORTS.NS':  {'name': 'Adani Ports',         'sector': 'Infrastructure',      'tier': 'large'},
    'ASIANPAINT.NS':  {'name': 'Asian Paints',         'sector': 'Consumer',            'tier': 'large'},
    'AXISBANK.NS':    {'name': 'Axis Bank',             'sector': 'Banking',             'tier': 'large'},
    'BAJAJ-AUTO.NS':  {'name': 'Bajaj Auto',            'sector': 'Auto',                'tier': 'large'},
    'BAJFINANCE.NS':  {'name': 'Bajaj Finance',         'sector': 'NBFC',                'tier': 'large'},
    'BAJAJFINSV.NS':  {'name': 'Bajaj Finserv',         'sector': 'NBFC',                'tier': 'large'},
    'BPCL.NS':        {'name': 'BPCL',                  'sector': 'Oil & Gas',           'tier': 'large'},
    'BHARTIARTL.NS':  {'name': 'Bharti Airtel',         'sector': 'Telecom',             'tier': 'large'},
    'BRITANNIA.NS':   {'name': 'Britannia',             'sector': 'FMCG',                'tier': 'large'},
    'CIPLA.NS':       {'name': 'Cipla',                 'sector': 'Pharma',              'tier': 'large'},
    'COALINDIA.NS':   {'name': 'Coal India',            'sector': 'Metals & Mining',     'tier': 'large'},
    'DIVISLAB.NS':    {'name': "Divi's Labs",           'sector': 'Pharma',              'tier': 'large'},
    'DRREDDY.NS':     {'name': 'Dr Reddy',              'sector': 'Pharma',              'tier': 'large'},
    'EICHERMOT.NS':   {'name': 'Eicher Motors',         'sector': 'Auto',                'tier': 'large'},
    'GRASIM.NS':      {'name': 'Grasim',                'sector': 'Cement',              'tier': 'large'},
    'HCLTECH.NS':     {'name': 'HCL Tech',              'sector': 'IT',                  'tier': 'large'},
    'HDFCBANK.NS':    {'name': 'HDFC Bank',             'sector': 'Banking',             'tier': 'large'},
    'HDFCLIFE.NS':    {'name': 'HDFC Life',             'sector': 'Insurance',           'tier': 'large'},
    'HEROMOTOCO.NS':  {'name': 'Hero MotoCorp',         'sector': 'Auto',                'tier': 'large'},
    'HINDALCO.NS':    {'name': 'Hindalco',              'sector': 'Metals & Mining',     'tier': 'large'},
    'HINDUNILVR.NS':  {'name': 'HUL',                   'sector': 'FMCG',                'tier': 'large'},
    'ICICIBANK.NS':   {'name': 'ICICI Bank',            'sector': 'Banking',             'tier': 'large'},
    'ITC.NS':         {'name': 'ITC',                   'sector': 'FMCG',                'tier': 'large'},
    'INDUSINDBK.NS':  {'name': 'IndusInd Bank',         'sector': 'Banking',             'tier': 'large'},
    'INFY.NS':        {'name': 'Infosys',               'sector': 'IT',                  'tier': 'large'},
    'JSWSTEEL.NS':    {'name': 'JSW Steel',             'sector': 'Metals & Mining',     'tier': 'large'},
    'KOTAKBANK.NS':   {'name': 'Kotak Bank',            'sector': 'Banking',             'tier': 'large'},
    'LT.NS':          {'name': 'L&T',                   'sector': 'Infrastructure',      'tier': 'large'},
    'M&M.NS':         {'name': 'M&M',                   'sector': 'Auto',                'tier': 'large'},
    'MARUTI.NS':      {'name': 'Maruti',                'sector': 'Auto',                'tier': 'large'},
    'NTPC.NS':        {'name': 'NTPC',                  'sector': 'Power',               'tier': 'large'},
    'NESTLEIND.NS':   {'name': 'Nestle',                'sector': 'FMCG',                'tier': 'large'},
    'ONGC.NS':        {'name': 'ONGC',                  'sector': 'Oil & Gas',           'tier': 'large'},
    'POWERGRID.NS':   {'name': 'Power Grid',            'sector': 'Power',               'tier': 'large'},
    'RELIANCE.NS':    {'name': 'Reliance',              'sector': 'Conglomerate',        'tier': 'large'},
    'SBILIFE.NS':     {'name': 'SBI Life',              'sector': 'Insurance',           'tier': 'large'},
    'SHRIRAMFIN.NS':  {'name': 'Shriram Finance',       'sector': 'NBFC',                'tier': 'large'},
    'SBIN.NS':        {'name': 'SBI',                   'sector': 'Banking',             'tier': 'large'},
    'SUNPHARMA.NS':   {'name': 'Sun Pharma',            'sector': 'Pharma',              'tier': 'large'},
    'TCS.NS':         {'name': 'TCS',                   'sector': 'IT',                  'tier': 'large'},
    'TATACONSUM.NS':  {'name': 'Tata Consumer',         'sector': 'FMCG',                'tier': 'large'},
    'TATASTEEL.NS':   {'name': 'Tata Steel',            'sector': 'Metals & Mining',     'tier': 'large'},
    'TECHM.NS':       {'name': 'Tech Mahindra',         'sector': 'IT',                  'tier': 'large'},
    'TITAN.NS':       {'name': 'Titan',                 'sector': 'Consumer',            'tier': 'large'},
    'ULTRACEMCO.NS':  {'name': 'UltraTech Cement',      'sector': 'Cement',              'tier': 'large'},
    'WIPRO.NS':       {'name': 'Wipro',                 'sector': 'IT',                  'tier': 'large'},
    'TRENT.NS':       {'name': 'Trent',                 'sector': 'Consumer',            'tier': 'large'},
    'BEL.NS':         {'name': 'BEL',                   'sector': 'Defence',             'tier': 'large'},
    'TATAMOTORS.NS':  {'name': 'Tata Motors',           'sector': 'Auto',                'tier': 'large'},
    'TATAPOWER.NS':   {'name': 'Tata Power',            'sector': 'Power',               'tier': 'large'},

    # ── NIFTY NEXT 50 ───────────────────────────────────────────────────────
    'ADANIENT.NS':    {'name': 'Adani Enterprises',     'sector': 'Conglomerate',        'tier': 'large'},
    'APOLLOHOSP.NS':  {'name': 'Apollo Hospitals',      'sector': 'Healthcare',          'tier': 'large'},
    'BAJAJHLDNG.NS':  {'name': 'Bajaj Holdings',        'sector': 'NBFC',                'tier': 'large'},
    'BOSCHLTD.NS':    {'name': 'Bosch',                 'sector': 'Auto',                'tier': 'large'},
    'CHOLAFIN.NS':    {'name': 'Chola Finance',         'sector': 'NBFC',                'tier': 'large'},
    'COLPAL.NS':      {'name': 'Colgate',               'sector': 'FMCG',                'tier': 'large'},
    'DMART.NS':       {'name': 'DMart',                 'sector': 'Retail',              'tier': 'large'},
    'GODREJCP.NS':    {'name': 'Godrej Consumer',       'sector': 'FMCG',                'tier': 'large'},
    'HAVELLS.NS':     {'name': 'Havells',               'sector': 'Consumer Electricals','tier': 'large'},
    'ICICIGI.NS':     {'name': 'ICICI Lombard',         'sector': 'Insurance',           'tier': 'large'},
    'ICICIPRULI.NS':  {'name': 'ICICI Pru Life',        'sector': 'Insurance',           'tier': 'large'},
    'INDIGO.NS':      {'name': 'IndiGo',                'sector': 'Aviation',            'tier': 'large'},
    'IRCTC.NS':       {'name': 'IRCTC',                 'sector': 'PSU Services',        'tier': 'large'},
    'JSWENERGY.NS':   {'name': 'JSW Energy',            'sector': 'Power',               'tier': 'large'},
    'MARICO.NS':      {'name': 'Marico',                'sector': 'FMCG',                'tier': 'large'},
    'MUTHOOTFIN.NS':  {'name': 'Muthoot Finance',       'sector': 'NBFC',                'tier': 'large'},
    'NAUKRI.NS':      {'name': 'Info Edge (Naukri)',    'sector': 'Technology',          'tier': 'large'},
    'NHPC.NS':        {'name': 'NHPC',                  'sector': 'Power',               'tier': 'large'},
    'OFSS.NS':        {'name': 'Oracle Financial',      'sector': 'IT',                  'tier': 'large'},
    'PIDILITIND.NS':  {'name': 'Pidilite',              'sector': 'Chemicals',           'tier': 'large'},
    'PIIND.NS':       {'name': 'PI Industries',         'sector': 'Agrochemicals',       'tier': 'large'},
    'RECLTD.NS':      {'name': 'REC',                   'sector': 'PSU Finance',         'tier': 'large'},
    'SIEMENS.NS':     {'name': 'Siemens',               'sector': 'Industrials',         'tier': 'large'},
    'SRF.NS':         {'name': 'SRF',                   'sector': 'Chemicals',           'tier': 'large'},
    'TORNTPHARM.NS':  {'name': 'Torrent Pharma',        'sector': 'Pharma',              'tier': 'large'},
    'TVSMOTOR.NS':    {'name': 'TVS Motor',             'sector': 'Auto',                'tier': 'large'},
    'VBL.NS':         {'name': 'Varun Beverages',       'sector': 'FMCG',                'tier': 'large'},
    'VEDL.NS':        {'name': 'Vedanta',               'sector': 'Metals & Mining',     'tier': 'large'},
    'ZYDUSLIFE.NS':   {'name': 'Zydus Lifesciences',    'sector': 'Pharma',              'tier': 'large'},
    'DIXON.NS':       {'name': 'Dixon Technologies',    'sector': 'Electronics',         'tier': 'large'},
    'MFSL.NS':        {'name': 'Max Financial',         'sector': 'Insurance',           'tier': 'large'},
    'CGPOWER.NS':     {'name': 'CG Power',              'sector': 'Industrials',         'tier': 'large'},
    'SOLARINDS.NS':   {'name': 'Solar Industries',      'sector': 'Defence',             'tier': 'large'},
    'OBEROIRLTY.NS':  {'name': 'Oberoi Realty',         'sector': 'Real Estate',         'tier': 'large'},
    'CUMMINSIND.NS':  {'name': 'Cummins India',         'sector': 'Industrials',         'tier': 'large'},
    'ABB.NS':         {'name': 'ABB India',             'sector': 'Industrials',         'tier': 'large'},
    'HAL.NS':         {'name': 'HAL',                   'sector': 'Defence',             'tier': 'large'},
    'BHEL.NS':        {'name': 'BHEL',                  'sector': 'Industrials',         'tier': 'large'},
    'MANKIND.NS':     {'name': 'Mankind Pharma',        'sector': 'Pharma',              'tier': 'large'},
    'ZOMATO.NS':      {'name': 'Zomato',                'sector': 'Technology',          'tier': 'large'},
    'LICI.NS':        {'name': 'LIC India',             'sector': 'Insurance',           'tier': 'large'},
    'LODHA.NS':       {'name': 'Lodha (Macrotech)',     'sector': 'Real Estate',         'tier': 'large'},
    'ADANIGREEN.NS':  {'name': 'Adani Green',           'sector': 'Power',               'tier': 'large'},

    # ── NIFTY MIDCAP 150 ────────────────────────────────────────────────────
    'ALKEM.NS':       {'name': 'Alkem Labs',            'sector': 'Pharma',              'tier': 'mid'},
    'APOLLOTYRE.NS':  {'name': 'Apollo Tyres',          'sector': 'Auto',                'tier': 'mid'},
    'ASHOKLEY.NS':    {'name': 'Ashok Leyland',         'sector': 'Auto',                'tier': 'mid'},
    'ASTRAL.NS':      {'name': 'Astral',                'sector': 'Chemicals',           'tier': 'mid'},
    'AUROPHARMA.NS':  {'name': 'Aurobindo Pharma',      'sector': 'Pharma',              'tier': 'mid'},
    'BALKRISIND.NS':  {'name': 'Balkrishna Industries', 'sector': 'Auto',                'tier': 'mid'},
    'BANDHANBNK.NS':  {'name': 'Bandhan Bank',          'sector': 'Banking',             'tier': 'mid'},
    'BANKBARODA.NS':  {'name': 'Bank of Baroda',        'sector': 'Banking',             'tier': 'mid'},
    'BHARATFORG.NS':  {'name': 'Bharat Forge',          'sector': 'Auto',                'tier': 'mid'},
    'BERGEPAINT.NS':  {'name': 'Berger Paints',         'sector': 'Consumer',            'tier': 'mid'},
    'CANBK.NS':       {'name': 'Canara Bank',           'sector': 'Banking',             'tier': 'mid'},
    'CDSL.NS':        {'name': 'CDSL',                  'sector': 'Financial Services',  'tier': 'mid'},
    'COFORGE.NS':     {'name': 'Coforge',               'sector': 'IT',                  'tier': 'mid'},
    'CONCOR.NS':      {'name': 'Container Corp',        'sector': 'Logistics',           'tier': 'mid'},
    'CROMPTON.NS':    {'name': 'Crompton Greaves Consumer','sector': 'Consumer Electricals','tier': 'mid'},
    'DALBHARAT.NS':   {'name': 'Dalmia Bharat',         'sector': 'Cement',              'tier': 'mid'},
    'DEEPAKNTR.NS':   {'name': 'Deepak Nitrite',        'sector': 'Chemicals',           'tier': 'mid'},
    'EMAMILTD.NS':    {'name': 'Emami',                 'sector': 'FMCG',                'tier': 'mid'},
    'ESCORTS.NS':     {'name': 'Escorts Kubota',        'sector': 'Auto',                'tier': 'mid'},
    'FEDERALBNK.NS':  {'name': 'Federal Bank',          'sector': 'Banking',             'tier': 'mid'},
    'GLAND.NS':       {'name': 'Gland Pharma',          'sector': 'Pharma',              'tier': 'mid'},
    'GODREJPROP.NS':  {'name': 'Godrej Properties',     'sector': 'Real Estate',         'tier': 'mid'},
    'GRANULES.NS':    {'name': 'Granules India',        'sector': 'Pharma',              'tier': 'mid'},
    'GUJGASLTD.NS':   {'name': 'Gujarat Gas',           'sector': 'Oil & Gas',           'tier': 'mid'},
    'HINDPETRO.NS':   {'name': 'HPCL',                  'sector': 'Oil & Gas',           'tier': 'mid'},
    'IDFCFIRSTB.NS':  {'name': 'IDFC First Bank',       'sector': 'Banking',             'tier': 'mid'},
    'IEX.NS':         {'name': 'IEX',                   'sector': 'Power',               'tier': 'mid'},
    'INDUSTOWER.NS':  {'name': 'Indus Towers',          'sector': 'Telecom',             'tier': 'mid'},
    'IPCALAB.NS':     {'name': 'IPCA Labs',             'sector': 'Pharma',              'tier': 'mid'},
    'IRFC.NS':        {'name': 'IRFC',                  'sector': 'PSU Finance',         'tier': 'mid'},
    'ISEC.NS':        {'name': 'ICICI Securities',      'sector': 'Financial Services',  'tier': 'mid'},
    'JKCEMENT.NS':    {'name': 'JK Cement',             'sector': 'Cement',              'tier': 'mid'},
    'KANSAINER.NS':   {'name': 'Kansai Nerolac',        'sector': 'Consumer',            'tier': 'mid'},
    'KPITTECH.NS':    {'name': 'KPIT Technologies',     'sector': 'IT',                  'tier': 'mid'},
    'LTIM.NS':        {'name': 'LTIMindtree',           'sector': 'IT',                  'tier': 'mid'},
    'LTTS.NS':        {'name': 'L&T Tech Services',     'sector': 'IT',                  'tier': 'mid'},
    'LUPIN.NS':       {'name': 'Lupin',                 'sector': 'Pharma',              'tier': 'mid'},
    'MANAPPURAM.NS':  {'name': 'Manappuram Finance',    'sector': 'NBFC',                'tier': 'mid'},
    'MAXHEALTH.NS':   {'name': 'Max Healthcare',        'sector': 'Healthcare',          'tier': 'mid'},
    'MCX.NS':         {'name': 'MCX',                   'sector': 'Financial Services',  'tier': 'mid'},
    'MPHASIS.NS':     {'name': 'Mphasis',               'sector': 'IT',                  'tier': 'mid'},
    'MRF.NS':         {'name': 'MRF',                   'sector': 'Auto',                'tier': 'mid'},
    'NATIONALUM.NS':  {'name': 'NALCO',                 'sector': 'Metals & Mining',     'tier': 'mid'},
    'NMDC.NS':        {'name': 'NMDC',                  'sector': 'Metals & Mining',     'tier': 'mid'},
    'PAGEIND.NS':     {'name': 'Page Industries',       'sector': 'Consumer',            'tier': 'mid'},
    'PERSISTENT.NS':  {'name': 'Persistent Systems',    'sector': 'IT',                  'tier': 'mid'},
    'PETRONET.NS':    {'name': 'Petronet LNG',          'sector': 'Oil & Gas',           'tier': 'mid'},
    'PNB.NS':         {'name': 'PNB',                   'sector': 'Banking',             'tier': 'mid'},
    'POLYCAB.NS':     {'name': 'Polycab',               'sector': 'Consumer Electricals','tier': 'mid'},
    'SAIL.NS':        {'name': 'SAIL',                  'sector': 'Metals & Mining',     'tier': 'mid'},
    'SONACOMS.NS':    {'name': 'Sona BLW Precision',    'sector': 'Auto',                'tier': 'mid'},
    'SUNDARMFIN.NS':  {'name': 'Sundaram Finance',      'sector': 'NBFC',                'tier': 'mid'},
    'SUPREMEIND.NS':  {'name': 'Supreme Industries',    'sector': 'Chemicals',           'tier': 'mid'},
    'SYNGENE.NS':     {'name': 'Syngene',               'sector': 'Pharma',              'tier': 'mid'},
    'TATACHEM.NS':    {'name': 'Tata Chemicals',        'sector': 'Chemicals',           'tier': 'mid'},
    'TATAELXSI.NS':   {'name': 'Tata Elxsi',            'sector': 'IT',                  'tier': 'mid'},
    'THERMAX.NS':     {'name': 'Thermax',               'sector': 'Industrials',         'tier': 'mid'},
    'TIINDIA.NS':     {'name': 'Tube Investments',      'sector': 'Industrials',         'tier': 'mid'},
    'TORNTPOWER.NS':  {'name': 'Torrent Power',         'sector': 'Power',               'tier': 'mid'},
    'UBL.NS':         {'name': 'United Breweries',      'sector': 'FMCG',                'tier': 'mid'},
    'UNIONBANK.NS':   {'name': 'Union Bank',            'sector': 'Banking',             'tier': 'mid'},
    'VOLTAS.NS':      {'name': 'Voltas',                'sector': 'Consumer Electricals','tier': 'mid'},
    'YESBANK.NS':     {'name': 'Yes Bank',              'sector': 'Banking',             'tier': 'mid'},
    'KALYANKJIL.NS':  {'name': 'Kalyan Jewellers',      'sector': 'Consumer',            'tier': 'mid'},
    'MOTILALOFS.NS':  {'name': 'Motilal Oswal',         'sector': 'Financial Services',  'tier': 'mid'},
    'CESC.NS':        {'name': 'CESC',                  'sector': 'Power',               'tier': 'mid'},
    'LTF.NS':         {'name': 'L&T Finance',           'sector': 'NBFC',                'tier': 'mid'},
    'AMBUJACEM.NS':   {'name': 'Ambuja Cements',        'sector': 'Cement',              'tier': 'mid'},
    'ACCLTD.NS':      {'name': 'ACC',                   'sector': 'Cement',              'tier': 'mid'},
    'BIOCON.NS':      {'name': 'Biocon',                'sector': 'Pharma',              'tier': 'mid'},
    'MOTHERSON.NS':   {'name': 'Samvardhana Motherson', 'sector': 'Auto',                'tier': 'mid'},
    'FORTIS.NS':      {'name': 'Fortis Healthcare',     'sector': 'Healthcare',          'tier': 'mid'},
    'PHOENIXLTD.NS':  {'name': 'Phoenix Mills',         'sector': 'Real Estate',         'tier': 'mid'},
    'HINDZINC.NS':    {'name': 'Hindustan Zinc',        'sector': 'Metals & Mining',     'tier': 'mid'},
    'BLUESTARCO.NS':  {'name': 'Blue Star',             'sector': 'Consumer Electricals','tier': 'mid'},
    'RBLBANK.NS':     {'name': 'RBL Bank',              'sector': 'Banking',             'tier': 'mid'},
    'UJJIVANSFB.NS':  {'name': 'Ujjivan SFB',           'sector': 'Banking',             'tier': 'mid'},
    'MAHABANK.NS':    {'name': 'Bank of Maharashtra',   'sector': 'Banking',             'tier': 'mid'},
    'NIACL.NS':       {'name': 'New India Assurance',   'sector': 'Insurance',           'tier': 'mid'},
    'SUNTV.NS':       {'name': 'Sun TV Network',        'sector': 'Media',               'tier': 'mid'},
    'JYOTHYLAB.NS':   {'name': 'Jyothy Labs',           'sector': 'FMCG',                'tier': 'mid'},
    'KFINTECH.NS':    {'name': 'KFin Technologies',     'sector': 'Financial Services',  'tier': 'mid'},
    'SCHAEFFLER.NS':  {'name': 'Schaeffler India',      'sector': 'Industrials',         'tier': 'mid'},
    'APLAPOLLO.NS':   {'name': 'APL Apollo Tubes',      'sector': 'Steel',               'tier': 'mid'},
    'ENGINERSIN.NS':  {'name': 'Engineers India',       'sector': 'Infrastructure',      'tier': 'mid'},
    'POONAWALLA.NS':  {'name': 'Poonawalla Fincorp',    'sector': 'NBFC',                'tier': 'mid'},
    'CANFINHOME.NS':  {'name': 'Can Fin Homes',         'sector': 'Housing Finance',     'tier': 'mid'},
    'BSE.NS':         {'name': 'BSE',                   'sector': 'Financial Services',  'tier': 'mid'},
    'KAYNES.NS':      {'name': 'Kaynes Technology',     'sector': 'Electronics',         'tier': 'mid'},
    'JSWINFRA.NS':    {'name': 'JSW Infrastructure',    'sector': 'Infrastructure',      'tier': 'mid'},
    'TATATECH.NS':    {'name': 'Tata Technologies',     'sector': 'IT',                  'tier': 'mid'},
    'STARHEALTH.NS':  {'name': 'Star Health Insurance', 'sector': 'Insurance',           'tier': 'mid'},
    'GSPL.NS':        {'name': 'GSPL',                  'sector': 'Oil & Gas',           'tier': 'mid'},
    'PRESTIGE.NS':    {'name': 'Prestige Estates',      'sector': 'Real Estate',         'tier': 'mid'},
    'DELHIVERY.NS':   {'name': 'Delhivery',             'sector': 'Logistics',           'tier': 'mid'},
    'SJVN.NS':        {'name': 'SJVN',                  'sector': 'Power',               'tier': 'mid'},
    'CHOLAHLDNG.NS':  {'name': 'Cholamandalam Holdings','sector': 'NBFC',                'tier': 'mid'},
    'POLICYBZR.NS':   {'name': 'PB Fintech (PolicyBazaar)','sector': 'Fintech',         'tier': 'mid'},
    'PAYTM.NS':       {'name': 'Paytm (One97)',         'sector': 'Fintech',             'tier': 'mid'},
}

# Quick lookups
SYMBOL_TO_NAME   = {k: v['name']   for k, v in NIFTY_250_STOCKS.items()}
SYMBOL_TO_SECTOR = {k: v['sector'] for k, v in NIFTY_250_STOCKS.items()}
SYMBOL_TO_TIER   = {k: v['tier']   for k, v in NIFTY_250_STOCKS.items()}
ALL_SYMBOLS      = list(NIFTY_250_STOCKS.keys())

SECTORS = sorted(set(v['sector'] for v in NIFTY_250_STOCKS.values()))
